services:
  postgres:
    container_name: re_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - $(pwd)/pg_hba.conf:/etc/postgresql/pg_hba.conf
