spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rulebase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        # Add MVEL validation properties
        mvel.strict: false
        mvel.compiler.strict: false
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    
# Add custom rule engine properties
rule-engine:
  mvel:
    strict-mode: false
    cache-expressions: true
    max-cache-size: 1000